# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49e426aed5cb99ba55c2e55c8cec12e79dc1973ad5950a7a617a9ca8fe13dede6deecd6a4c4b965accce1781e33723661d90b3f81a26de37cd3434f54b961af0

test:
  secret_key_base: 58f79d7afc2f6082031fc4ae61449a78f61276a4d5ea6dc14008d962b8321eea0d01c34dba3dae7c89678efe1769a62002a8f5d664171ad0a713d82c6f98e08f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
